# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        su::TimeBoxx
    description:  Open source project timetracking software
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    []

  javascripts:    [jquery.min.js]

  has_layout:     true
  layout:         layout
